### PR TITLE
wallet: fix a pile of bugs in transaction funding logic

### LINKED ISSUE #1049: Dummy output is added to PSET outputs even if it's not necessary
I encountered an issue when creating PSET with max amount. Elements always adds a third dummy OP_RETURN output, but never blinds it. When confidential address is used - it just adds unnecessary dummy output, if unconfidential address is used - `walletprocesspsbt` that should blind the transaction fails with an error.

So I assume the fix should be:
- do not add dummy output if confidential address is used
- add dummy output if unconfidential address is used but also add a dummy blinding pubkey for blinding this output at later stage with `walletprocesspsbt`.

# Sending max amount to confidential address:

I have a wallet with 1 BTC on it in a single utxo. I am creating a PSET transaction sending everything to a confidential address so there is no change:

```
elements-cli -rpcwallet="specter/elhot" walletcreatefundedpsbt '[]' '[{"el1qqfwe26qwshlwnmy7gt3htp2g0jpxrmurpnvrz7nmfwsgpt89xclttccpwplctud9ngt9euzya8ahqhgs56uaynvfs4gnunu4q":1}]' 0 '{"subtractFeeFromOutputs": [0]}'
```

The resulting PSET has 3 outputs:
1. to confidential address, 
2. fee
3. OP_RETURN with 0 amount - I think it shouldn't be there.

PSET:
```
cHNldP8BAgQCAAAAAQMEAAAAAAEEAQEBBQEDAfsEAgAAAAABAP1UAQIAAAAAAXKOYwMwh49bV2qfeUsTe9agKCrHQkLEMs8FzB2HrUtJAAAAAAD9////AwqKEnAS0MBnZYTFfUoP6NND58xujFcpdFGJn6jkmP5bKghVitzQljWmsm9a/jKieTM32i0uYzIs7iFFrHoiAo6hygPNvtXL8CkMTYU6NIblZVlTTqW0W7ngualdBgAoOM9+2RYAFE3LimuS493jFkqwcBm+3GoDkIBcC4TZqgZpCKjTFIAtRXVVx2Y2qiw6t9OJ+VPFwPZFrmtCCDlW5q5qzQj9vuKFUmZF9nrVutauM0mkDNrxwjY87rY+A/7ZCCrUiwlQD69DwptL4gJkRXx16HOWIUocDwTWGyIeFgAUYh7hzYM+GnO+Rfjn4bCg6Q6e7/ABGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMBAAAAAAAAAPkAAG8AAAABAXoLhNmqBmkIqNMUgC1FdVXHZjaqLDq304n5U8XA9kWua0IIOVbmrmrNCP2+4oVSZkX2etW61q4zSaQM2vHCNjzutj4D/tkIKtSLCVAPr0PCm0viAmRFfHXoc5YhShwPBNYbIh4WABRiHuHNgz4ac75F+OfhsKDpDp7v8CIGApikxBz8OF8sSRt6iG6Id77oOwuaGk+jD3gv1CoL3URQGBcg4JJUAACAAQAAgAAAAIAAAAAAAQAAAAEOIDNrizsvReAipbb10BHWS42l4zwFo0IkQS7zScoQlhGbAQ8EAQAAAAEQBP3///8H/ARwc2V0Dv1OEGAzAAAAAAAAAAGFYrAAfBmK6wBQQduL33w7RsHkD6sVxb4rgJip+DXAEYD1eCc9HIiHxBEepEgHKUfDb0tRyJjGBhzG2HXFA43/u4A8+cOiiKyJ6qdi/ou4gq/C1OcoDcg34SZ9aSGdIPIneSsn6ZJ5JqGJZpClzxFtIDC9SobgGsVnHvlX7jpqf5aqbH446SAvBX3WsetfuXeEnw4gxALjGyBO1Eh7Fs8H5bvnV1rQYmsZ7CGC1TupWJYQ7IwTTng7hTgMUk4+9erNtM5Czq6mA4pJpJtlB6jFfhhPvnQYqeOD8LLd6g/QPVhcPY59klBFDJFvKxM1TzIuE7BiBRHth7RFB3pJSjYt7LWHpFiFoFa/ZUhgDuQdl7c2O0hxR7LAeGDcG8z/prMjC96XEbeLQm+YD/evZZaF7aL2lTZtApvCgoaLd0YOSPmKX7US3WXEcU1jOh1QxNHrJxdPPb1ZBsTEFqCREoSzL9rZcbYMI3S6PqF83CkoVb1K86W+W2Sseih3rSdcl2gflaZvb4wy8tQVZoZYZLUzns/KEhuXEw5UD8Hq14qe7UCTgPCY5JLEcjML8M8FI+3Ajjv+/OIBaHgv0kSY878f0LNhOpYrodt2wiQiHqQCUgXrrN4vTtrBBsyMnAg+nukEzCXiBLoJL4UUyMdhbWTihE95HLig40LK8/GIKqrSotBCqoTr6Hj+RWO/8Ri1rWnHzjqfBJgu2xKeXe/8Bhn/DIgHA6rY8o9JeheP5h2Y96jgxKZhbf0oX+9vPDTn7XjOYyRrMYDlzKBlL1Ep4fsENsFRk78iSh5AXfPC4uRPlZn4EaOyU8MAHLWdoTX/Sl/wXLczwvH7L9Gw13ChQh7QN5mbuALdaoNnaMgPrm8c5jicCXe42xKRcrv+B/sqmZRCkuYLmQMgp4QPcUKz4qnVUQQiL1/wpcj5Q9wXI9zNIArZtnEBLrrZuF3bVH8CYf4FtndgxIt5iFNOo+Xzlqej81iyrU6roRI+cety4YRGNx0M4WT6eluo4LlWWSUgAuwmNjLdRr13EsxKJCQ6oWAy1eo6Fh8IhNl5lUtH6ROVbL3sIZRuA+u0Q8rnamzTj6b94nJeTt6gjXqHEWYTOXI1OxqdHCtb9NSPIK9AVnrkP6tvpZD9uGLGTG4KYkFZJV+30A63U5WUahgZ9HvYHn8KfCAPg4lceIHjbYFQhw7/aZs6yUNPGpRxnyEGN2XYaUgVqhxUget3GDuQWCzWgUu7g5YKkOQWd93hR+YFVUMPuZLld/eAEAXgKUNovn4BEdFzJAaHqJW8sfRw3aV8MHS4HsHg4e0kZ5eK3n1VHbIi5UUe58Dg9m2s5S3BSMTfntN53umDgLxw2oeA6fzU3U1XbBe9Q7e/1znjA+fvUjmgysGbaAov1g/VoZ/vEhMExrCRCpnRVSC2hJ1fnhMqY2Ur0irznc/Hb5UTs+roxPcp8wu+GPUczqbRyKAXP+Dsr1/Ml/IsqW23RfaUYvag1GT8iZTP+4ZaZIL4Ghs//zGKaoSnAr6n8Xl4WexN3pNtBmORF+LKs8LW4cX/N96W8Ta4bIutmj12Os9Y3DSUD4aqfE0BGjBbtplnYjZdt9PVdzMOeyXsuS9PoYNvFuE1ovOOIbOZwiAkdrx+f5QXmBsxoaFYR/WSaDWieeqz3D6jpWC4KYUYSinp4T/OLlW8iqW5UJmM4+iLIJTSOFd7UHHje2QWIPiQlHvLMOio4zvVwOEsEXxCHqPzuwVIZXHsAqx6TgcuGL7kyCGsXGT0NLpIbootbTaDQEuKAogj5lEhj3bpcg1jsG9aVJx51672IHqIFUJy8okgUdIAJ6NrXjPU3SjYo/kdxY9DaJWbvgA5LjDmQUn04vX6DJ1p7u3A+lXnMNqAnl6tQwkhsUyM2yz1acmE1HFKKBYYqgTay31Nyj48LCBgaCk7zq2XqARIAOBIj0UGqR781fcEiO7WDuFqUBXn2LBmJfIfOLDEKBIq+xYP0D9bNM4WKLHrPQ+t06u5S1EctZGUqz3DBDb/S+u28PVPa1R63AFM5Y5brWQB2o8SArl+QgitOX0HL2KKjqg0ELaPf2yRLsLxpfGdJ+UZ3InV3Pn4/EMruc21gT6f6KREwc0evuDoRpQ2n7UrE0OVwfrYcqDMpmLna93+o9CI3lNUO9I22XMiYzPxTmy8OGJ946tap1laErwG9eJPGFCgFsKXCTE2chs6s/3FSjSZ8RzyjShg93dgigEXveEuFnHwIbXZGythjYWwDxAoJpaIO+hjJwcG0blzNCy15NhrK+faSJ1yauTs+m7lHvxigX/n16IQxLbxW87HAhxj9J+9OZtxUy5UhqLv1dA15LDpYJrGeRMsLj3iG8CmuGT9KdMDEaEdBfAAn7xXF1FchNS6hc/FQlX7/K/bWAo8bF/RJ1aWcBhLkT0c/7pgrbXiq6Q1gy5ZILozYFR/n/lsYV3tej829k8qvbz39xdns6Sij8N1AN6VKzVHo1ZImdwVQDAiCQvGZQIG8HvBjrdgdekqIHcLe3iNaXPUNT0/8bhkKAii2wB43vpTHof3lgUZTpd6FuoEsD8ii9H56otBUrZyeypS15BepvskxQjjLALintjy9yemm/SuaImRpnhj11IiOd0zZxOdqLxkFgniyEhPXPZcbAJdwpn2QuJuiVLRrwwA+DDH9eGxN0kS0vcaYClPyYMvNHB2fCK5yOMSpxteMdANeSUnWIlxgLhSMLlV12gcQegmx8w336FX9+gtXmLv287jlFWmPCOBgwJT6L/lJ0Fy8AWeGDCdJNQtEpZ7mqMvhVso/fc4Q3e6USR+TcjlfPVgrUt38chu9n+XLZ9UOYW1MjwBtKcsolnJk6sfO8ZbJ/Zdk4cQ0eL/N+5ftK3z5ziKtag/q/AMtHDePNTkA/gmzSpjjSFvHB5V+1NPrLwmxrUAxvwBv+GRoVGt/bXeYpG3rwe3Z+HeZwNHGNKTMssao/eyTV7e7EBbmaxtVtu6G8alS8k66+1+sHhZc2xNj1M1go1lTHJtc0/UifnPWolKusjTJHKyrheTO9G/7pbsvsItyiiv056BYne8O2/AVKTHqGG/WiQhH4JK8bLRhQKbCthCv5CMiVFbqCVrRPHi9YIttYZpshp/QjVBEUbLA0lLgaenNKaLV8fp4+uL73ls/erVW0WnU4+DXiJ5Jlhxpwyqi6Tzi8x5sxaATP+NVNG6Wm/MlWnLT9Tmxp6+YDvzBPnwQ9o/ISRiKrxVyn2iNUt9EM9SVq/nsF0FjPKC0R5lmyGPx8mbUnO9w15xnQ+vvF1+kYMOchsSAm+I33PyiMQ5Uj8q5eQm5rmalNk3vTMtIv03OLd1JFlRio+XoYrMUomrb2EKBiVPbL2Xld2S5trOyqPkxn6JrFHnZoMuB97JYRFvcbl64I8dh0MwklwYXHErLRIlvQZJp35YMRcVgnMqpvqCC8CfkKV8OAzkQL9TPbPW0Fa5onlg6WCz0/SmHbbN3S1dL120yyKGMSpbKFBl9Z3TmJZnAIwGxHdWIyNOJJ08MSsUEq6a9jgPcCHVZ8ECxjtLEfu/TexVHw6l/2bNR0Eb1HKiGdVmtcWC4s3KAYSySS07kSUYlEqDA+T8qjPauj5rPYjc7L8K2rIinJBk7ez4cs7Gnmh2ikL4AeJR5K85gPrUfFg5jU2NrrpqAJDkDcnNnSDsoz4bXsQOOrz6eznbPKyqYNQn+ivfDc4MXCPMVWzPSQjU9sALTVMCMCN6dShrKamAnUciPL8KQX4pusE4Z42RhuBTx+B43p1KO/P1HrHtASzWn9jyfqONWtkkmuVF7mng0Wn0je8Fpf33af6jkoeqzKsWImKtp911omzuc/kLe1mvdIsSZTA/j3VpD9bAvSnd29lRiHWI24Y+AixiM59ONpbbQ+DCuaP/LlnYuic/3GhP9hPOcA2uHMkVRqwvn+kbQTapdEBFWXV62NY3wScBCg+sewDkRVOWps9wL8rd5FdMfBWs2igNFrFiFvytsN89XiPFAIP5AdIWFE0FWtMzaGcNNmyF4ubxITUze2bAJRBXRDHCnWVsI+ldQE26qTlRZzXP56RvYUDy3pu/hqieHOWu0ktWRYOmNgySSTAiR4FCj8zj2CDxbYRyPYOFKm4Stjsv5RQooCXO5pNKL8P6pOhpH7QkCtSNBpYokzzNEax80f8o5gG7xkrLQ0qsUc0ZmpX0Y/FB0PvyMMMtety/IPwpaWJSr8x+Qg7JBwpJQt2fWX6gTygn25jn6sBU3aptn02Hn9IOkUypKZnNxpvyhSBYe8sBNb/QNs6PBBhmrAl/2Mz5psOC6pak3UCVQIDdxV/6TQ3qEbzrs7WSQRRI4jrHflu2bWJSiwP1zVdHmQM+F+GtsFJS8RdSSIaa0gcxGDz0O4X307rzp+iApb5eZSVnL+KZda2Z9u6Lv6gON/S8vG5FAf9MhU3O4R/3ZxgGcTlIrKZ6fBTaHvaPsLMN09Gvg5VQH1qBHtp7Md4QyN1Y61ELXj/kykw6GxVc4rBKrPjK0I6aVu9n4dVzcObOswaid+j/QuX1sBmb0hNHzLVOLmMzkc2Q6tlj4BREtvRJz34tW0cvBNEew7E+QyGD6R4Twx+r/1L5SDqYYcff5amgbt1e+bBQRSZnr/7IUN+2LGKLBnRokwLvc53ZjklMcLvF6dErWcdavc3JtONoJY9tcEZNUinNBUEr4fTQIGBuV1yIA7qu2P7SIxiL9n80QyS897rY3nltzkoCXcoNnSwXsabyXlHnAKrWJzTzh84rm2cnDIcDB4Pef6nRZvLcdADRzmt5h3Aq6WvP7taWkwkpgWhZnnQd7JUUYlejhh145Ip0rDKelQfayawNKoHk8ESPA6LOenFqqhdwOG1LL2wvTr1pWn3SoFO2MSyP3U5/c39/f1QKtcxNg0cNY2ati8GhNCpSmHF7AhgnhD9XOk4tSTF8x1FRUpy/PQdDYdQnzRizXSf8q3M7XGcfsyLv5TRH7HfU++JU5LI7hXiCbZIqggTl2Zh/Fw1Y+FfYUJnXypRJC8CkAonBAPD8nvy+EvYq8uvPBqhDL8PeHHNIaMyJu6DxutvNa3satjfehuF6qfJ5wdDMkEo/ASzZfUgh6J/xCBmS9oJkHUjIDXHrQev5UM7zGfCkdiY6jjbiui+7L0EFB/QVwBl+jkbIk7Mn6WT39OZCIFLu8o/YcCHTyJ4AMgAfG+BrBSyIZc6vow2YKa7PK2ddAgQAwNmsKh//KRGPesvy1a79SED/2DOM5lt8eN8xnpLIJkntsKVoy8hCDiBQfGRsRX4jB464i7aPa5BvR/Et53Di7s5VMED0R8GnVeq3yEAsXTVtwAXGpA/2TeQOjAQD0W41g8bn4UhzuFzikED+TzUVL49w0+V6A7zmeSuDurrVizSqKGQB0iwO/ggOObOBFj/JKDOAE9vEqqC0eYZa7GXBvEvIH/u3cY3z1sVHlmqfcVLSu6enmC+JbjWOnXEgp9xdIxULsd9FR8NkF+GN2XRtgn1qFh6Gbb1XcidP0w2Pd+NrMdMS/DCe3n1luCiaqEkAAQQWABTjAXB/hfGlmhZc8ETp+3BdEKa50gEDCHng9QUAAAAAB/wEcHNldAIgGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMH/ARwc2V0BiECXZVoDoX+6eyeQuN1hUh8gmHvgwzYMXp7S6CArOU2PrUH/ARwc2V0CAQAAAAAAAEEAAEDCIcAAAAAAAAAB/wEcHNldAIgGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMH/ARwc2V0CAQAAAAAAAEEAWoBAwgAAAAAAAAAAAf8BHBzZXQCIBhpbPI+Mgmm6ER50B8T/nnJATVq5TkHzIgs/9PiZAEjB/wEcHNldAgEAAAAAAA=
```

Then `walletprocesspsbt` only blinds output 0. When signed and finalized the raw transaction still contains a third unblinded output with 0 amount.

# Sending to unconfidential address

The same using unconfidential address:

```
elements-cli -rpcwallet="specter/elhot" walletcreatefundedpsbt '[]' '[{"ert1quvqhqlu97xje59ju7pzwn7mst5g2dwwjer0xvh":1}]' 0 '{"subtractFeeFromOutputs": [0]}'
```

PSET:
```
cHNldP8BAgQCAAAAAQMEAAAAAAEEAQEBBQEDAfsEAgAAAAABAP1UAQIAAAAAAXKOYwMwh49bV2qfeUsTe9agKCrHQkLEMs8FzB2HrUtJAAAAAAD9////AwqKEnAS0MBnZYTFfUoP6NND58xujFcpdFGJn6jkmP5bKghVitzQljWmsm9a/jKieTM32i0uYzIs7iFFrHoiAo6hygPNvtXL8CkMTYU6NIblZVlTTqW0W7ngualdBgAoOM9+2RYAFE3LimuS493jFkqwcBm+3GoDkIBcC4TZqgZpCKjTFIAtRXVVx2Y2qiw6t9OJ+VPFwPZFrmtCCDlW5q5qzQj9vuKFUmZF9nrVutauM0mkDNrxwjY87rY+A/7ZCCrUiwlQD69DwptL4gJkRXx16HOWIUocDwTWGyIeFgAUYh7hzYM+GnO+Rfjn4bCg6Q6e7/ABGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMBAAAAAAAAAPkAAG8AAAABAXoLhNmqBmkIqNMUgC1FdVXHZjaqLDq304n5U8XA9kWua0IIOVbmrmrNCP2+4oVSZkX2etW61q4zSaQM2vHCNjzutj4D/tkIKtSLCVAPr0PCm0viAmRFfHXoc5YhShwPBNYbIh4WABRiHuHNgz4ac75F+OfhsKDpDp7v8CIGApikxBz8OF8sSRt6iG6Id77oOwuaGk+jD3gv1CoL3URQGBcg4JJUAACAAQAAgAAAAIAAAAAAAQAAAAEOIDNrizsvReAipbb10BHWS42l4zwFo0IkQS7zScoQlhGbAQ8EAQAAAAEQBP3///8H/ARwc2V0Dv1OEGAzAAAAAAAAAAGFYrAAfBmK6wBQQduL33w7RsHkD6sVxb4rgJip+DXAEYD1eCc9HIiHxBEepEgHKUfDb0tRyJjGBhzG2HXFA43/u4A8+cOiiKyJ6qdi/ou4gq/C1OcoDcg34SZ9aSGdIPIneSsn6ZJ5JqGJZpClzxFtIDC9SobgGsVnHvlX7jpqf5aqbH446SAvBX3WsetfuXeEnw4gxALjGyBO1Eh7Fs8H5bvnV1rQYmsZ7CGC1TupWJYQ7IwTTng7hTgMUk4+9erNtM5Czq6mA4pJpJtlB6jFfhhPvnQYqeOD8LLd6g/QPVhcPY59klBFDJFvKxM1TzIuE7BiBRHth7RFB3pJSjYt7LWHpFiFoFa/ZUhgDuQdl7c2O0hxR7LAeGDcG8z/prMjC96XEbeLQm+YD/evZZaF7aL2lTZtApvCgoaLd0YOSPmKX7US3WXEcU1jOh1QxNHrJxdPPb1ZBsTEFqCREoSzL9rZcbYMI3S6PqF83CkoVb1K86W+W2Sseih3rSdcl2gflaZvb4wy8tQVZoZYZLUzns/KEhuXEw5UD8Hq14qe7UCTgPCY5JLEcjML8M8FI+3Ajjv+/OIBaHgv0kSY878f0LNhOpYrodt2wiQiHqQCUgXrrN4vTtrBBsyMnAg+nukEzCXiBLoJL4UUyMdhbWTihE95HLig40LK8/GIKqrSotBCqoTr6Hj+RWO/8Ri1rWnHzjqfBJgu2xKeXe/8Bhn/DIgHA6rY8o9JeheP5h2Y96jgxKZhbf0oX+9vPDTn7XjOYyRrMYDlzKBlL1Ep4fsENsFRk78iSh5AXfPC4uRPlZn4EaOyU8MAHLWdoTX/Sl/wXLczwvH7L9Gw13ChQh7QN5mbuALdaoNnaMgPrm8c5jicCXe42xKRcrv+B/sqmZRCkuYLmQMgp4QPcUKz4qnVUQQiL1/wpcj5Q9wXI9zNIArZtnEBLrrZuF3bVH8CYf4FtndgxIt5iFNOo+Xzlqej81iyrU6roRI+cety4YRGNx0M4WT6eluo4LlWWSUgAuwmNjLdRr13EsxKJCQ6oWAy1eo6Fh8IhNl5lUtH6ROVbL3sIZRuA+u0Q8rnamzTj6b94nJeTt6gjXqHEWYTOXI1OxqdHCtb9NSPIK9AVnrkP6tvpZD9uGLGTG4KYkFZJV+30A63U5WUahgZ9HvYHn8KfCAPg4lceIHjbYFQhw7/aZs6yUNPGpRxnyEGN2XYaUgVqhxUget3GDuQWCzWgUu7g5YKkOQWd93hR+YFVUMPuZLld/eAEAXgKUNovn4BEdFzJAaHqJW8sfRw3aV8MHS4HsHg4e0kZ5eK3n1VHbIi5UUe58Dg9m2s5S3BSMTfntN53umDgLxw2oeA6fzU3U1XbBe9Q7e/1znjA+fvUjmgysGbaAov1g/VoZ/vEhMExrCRCpnRVSC2hJ1fnhMqY2Ur0irznc/Hb5UTs+roxPcp8wu+GPUczqbRyKAXP+Dsr1/Ml/IsqW23RfaUYvag1GT8iZTP+4ZaZIL4Ghs//zGKaoSnAr6n8Xl4WexN3pNtBmORF+LKs8LW4cX/N96W8Ta4bIutmj12Os9Y3DSUD4aqfE0BGjBbtplnYjZdt9PVdzMOeyXsuS9PoYNvFuE1ovOOIbOZwiAkdrx+f5QXmBsxoaFYR/WSaDWieeqz3D6jpWC4KYUYSinp4T/OLlW8iqW5UJmM4+iLIJTSOFd7UHHje2QWIPiQlHvLMOio4zvVwOEsEXxCHqPzuwVIZXHsAqx6TgcuGL7kyCGsXGT0NLpIbootbTaDQEuKAogj5lEhj3bpcg1jsG9aVJx51672IHqIFUJy8okgUdIAJ6NrXjPU3SjYo/kdxY9DaJWbvgA5LjDmQUn04vX6DJ1p7u3A+lXnMNqAnl6tQwkhsUyM2yz1acmE1HFKKBYYqgTay31Nyj48LCBgaCk7zq2XqARIAOBIj0UGqR781fcEiO7WDuFqUBXn2LBmJfIfOLDEKBIq+xYP0D9bNM4WKLHrPQ+t06u5S1EctZGUqz3DBDb/S+u28PVPa1R63AFM5Y5brWQB2o8SArl+QgitOX0HL2KKjqg0ELaPf2yRLsLxpfGdJ+UZ3InV3Pn4/EMruc21gT6f6KREwc0evuDoRpQ2n7UrE0OVwfrYcqDMpmLna93+o9CI3lNUO9I22XMiYzPxTmy8OGJ946tap1laErwG9eJPGFCgFsKXCTE2chs6s/3FSjSZ8RzyjShg93dgigEXveEuFnHwIbXZGythjYWwDxAoJpaIO+hjJwcG0blzNCy15NhrK+faSJ1yauTs+m7lHvxigX/n16IQxLbxW87HAhxj9J+9OZtxUy5UhqLv1dA15LDpYJrGeRMsLj3iG8CmuGT9KdMDEaEdBfAAn7xXF1FchNS6hc/FQlX7/K/bWAo8bF/RJ1aWcBhLkT0c/7pgrbXiq6Q1gy5ZILozYFR/n/lsYV3tej829k8qvbz39xdns6Sij8N1AN6VKzVHo1ZImdwVQDAiCQvGZQIG8HvBjrdgdekqIHcLe3iNaXPUNT0/8bhkKAii2wB43vpTHof3lgUZTpd6FuoEsD8ii9H56otBUrZyeypS15BepvskxQjjLALintjy9yemm/SuaImRpnhj11IiOd0zZxOdqLxkFgniyEhPXPZcbAJdwpn2QuJuiVLRrwwA+DDH9eGxN0kS0vcaYClPyYMvNHB2fCK5yOMSpxteMdANeSUnWIlxgLhSMLlV12gcQegmx8w336FX9+gtXmLv287jlFWmPCOBgwJT6L/lJ0Fy8AWeGDCdJNQtEpZ7mqMvhVso/fc4Q3e6USR+TcjlfPVgrUt38chu9n+XLZ9UOYW1MjwBtKcsolnJk6sfO8ZbJ/Zdk4cQ0eL/N+5ftK3z5ziKtag/q/AMtHDePNTkA/gmzSpjjSFvHB5V+1NPrLwmxrUAxvwBv+GRoVGt/bXeYpG3rwe3Z+HeZwNHGNKTMssao/eyTV7e7EBbmaxtVtu6G8alS8k66+1+sHhZc2xNj1M1go1lTHJtc0/UifnPWolKusjTJHKyrheTO9G/7pbsvsItyiiv056BYne8O2/AVKTHqGG/WiQhH4JK8bLRhQKbCthCv5CMiVFbqCVrRPHi9YIttYZpshp/QjVBEUbLA0lLgaenNKaLV8fp4+uL73ls/erVW0WnU4+DXiJ5Jlhxpwyqi6Tzi8x5sxaATP+NVNG6Wm/MlWnLT9Tmxp6+YDvzBPnwQ9o/ISRiKrxVyn2iNUt9EM9SVq/nsF0FjPKC0R5lmyGPx8mbUnO9w15xnQ+vvF1+kYMOchsSAm+I33PyiMQ5Uj8q5eQm5rmalNk3vTMtIv03OLd1JFlRio+XoYrMUomrb2EKBiVPbL2Xld2S5trOyqPkxn6JrFHnZoMuB97JYRFvcbl64I8dh0MwklwYXHErLRIlvQZJp35YMRcVgnMqpvqCC8CfkKV8OAzkQL9TPbPW0Fa5onlg6WCz0/SmHbbN3S1dL120yyKGMSpbKFBl9Z3TmJZnAIwGxHdWIyNOJJ08MSsUEq6a9jgPcCHVZ8ECxjtLEfu/TexVHw6l/2bNR0Eb1HKiGdVmtcWC4s3KAYSySS07kSUYlEqDA+T8qjPauj5rPYjc7L8K2rIinJBk7ez4cs7Gnmh2ikL4AeJR5K85gPrUfFg5jU2NrrpqAJDkDcnNnSDsoz4bXsQOOrz6eznbPKyqYNQn+ivfDc4MXCPMVWzPSQjU9sALTVMCMCN6dShrKamAnUciPL8KQX4pusE4Z42RhuBTx+B43p1KO/P1HrHtASzWn9jyfqONWtkkmuVF7mng0Wn0je8Fpf33af6jkoeqzKsWImKtp911omzuc/kLe1mvdIsSZTA/j3VpD9bAvSnd29lRiHWI24Y+AixiM59ONpbbQ+DCuaP/LlnYuic/3GhP9hPOcA2uHMkVRqwvn+kbQTapdEBFWXV62NY3wScBCg+sewDkRVOWps9wL8rd5FdMfBWs2igNFrFiFvytsN89XiPFAIP5AdIWFE0FWtMzaGcNNmyF4ubxITUze2bAJRBXRDHCnWVsI+ldQE26qTlRZzXP56RvYUDy3pu/hqieHOWu0ktWRYOmNgySSTAiR4FCj8zj2CDxbYRyPYOFKm4Stjsv5RQooCXO5pNKL8P6pOhpH7QkCtSNBpYokzzNEax80f8o5gG7xkrLQ0qsUc0ZmpX0Y/FB0PvyMMMtety/IPwpaWJSr8x+Qg7JBwpJQt2fWX6gTygn25jn6sBU3aptn02Hn9IOkUypKZnNxpvyhSBYe8sBNb/QNs6PBBhmrAl/2Mz5psOC6pak3UCVQIDdxV/6TQ3qEbzrs7WSQRRI4jrHflu2bWJSiwP1zVdHmQM+F+GtsFJS8RdSSIaa0gcxGDz0O4X307rzp+iApb5eZSVnL+KZda2Z9u6Lv6gON/S8vG5FAf9MhU3O4R/3ZxgGcTlIrKZ6fBTaHvaPsLMN09Gvg5VQH1qBHtp7Md4QyN1Y61ELXj/kykw6GxVc4rBKrPjK0I6aVu9n4dVzcObOswaid+j/QuX1sBmb0hNHzLVOLmMzkc2Q6tlj4BREtvRJz34tW0cvBNEew7E+QyGD6R4Twx+r/1L5SDqYYcff5amgbt1e+bBQRSZnr/7IUN+2LGKLBnRokwLvc53ZjklMcLvF6dErWcdavc3JtONoJY9tcEZNUinNBUEr4fTQIGBuV1yIA7qu2P7SIxiL9n80QyS897rY3nltzkoCXcoNnSwXsabyXlHnAKrWJzTzh84rm2cnDIcDB4Pef6nRZvLcdADRzmt5h3Aq6WvP7taWkwkpgWhZnnQd7JUUYlejhh145Ip0rDKelQfayawNKoHk8ESPA6LOenFqqhdwOG1LL2wvTr1pWn3SoFO2MSyP3U5/c39/f1QKtcxNg0cNY2ati8GhNCpSmHF7AhgnhD9XOk4tSTF8x1FRUpy/PQdDYdQnzRizXSf8q3M7XGcfsyLv5TRH7HfU++JU5LI7hXiCbZIqggTl2Zh/Fw1Y+FfYUJnXypRJC8CkAonBAPD8nvy+EvYq8uvPBqhDL8PeHHNIaMyJu6DxutvNa3satjfehuF6qfJ5wdDMkEo/ASzZfUgh6J/xCBmS9oJkHUjIDXHrQev5UM7zGfCkdiY6jjbiui+7L0EFB/QVwBl+jkbIk7Mn6WT39OZCIFLu8o/YcCHTyJ4AMgAfG+BrBSyIZc6vow2YKa7PK2ddAgQAwNmsKh//KRGPesvy1a79SED/2DOM5lt8eN8xnpLIJkntsKVoy8hCDiBQfGRsRX4jB464i7aPa5BvR/Et53Di7s5VMED0R8GnVeq3yEAsXTVtwAXGpA/2TeQOjAQD0W41g8bn4UhzuFzikED+TzUVL49w0+V6A7zmeSuDurrVizSqKGQB0iwO/ggOObOBFj/JKDOAE9vEqqC0eYZa7GXBvEvIH/u3cY3z1sVHlmqfcVLSu6enmC+JbjWOnXEgp9xdIxULsd9FR8NkF+GN2XRtgn1qFh6Gbb1XcidP0w2Pd+NrMdMS/DCe3n1luCiaqEkAAQQWABTjAXB/hfGlmhZc8ETp+3BdEKa50gEDCHng9QUAAAAAB/wEcHNldAIgGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMH/ARwc2V0CAQAAAAAAAEEAAEDCIcAAAAAAAAAB/wEcHNldAIgGGls8j4yCaboRHnQHxP+eckBNWrlOQfMiCz/0+JkASMH/ARwc2V0CAQAAAAAAAEEAWoBAwgAAAAAAAAAAAf8BHBzZXQCIBhpbPI+Mgmm6ER50B8T/nnJATVq5TkHzIgs/9PiZAEjB/wEcHNldAgEAAAAAAA=
```

Result also has 3 outputs. But `walletprocesspsbt` returns an error:
```
error code: -25
error message:
Transaction values or blinders are not balanced
```

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #1049 

Needs backport to 0.21 (and a new rc).

Although there are several bugs here, none affect the functionaries. There is a more thorough summary in the second-to-last commit message.

### CODE REVIEW

**Comment by stepansnigirev** [comment]
Tested, works now. Thanks!

**Comment by apoelstra** [comment]
Added an extra test I'd overlooked (which passed).

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -4957,8 +4957,16 @@ static RPCHelpMan walletcreatefundedpsbt()
...
     coin_control.m_add_inputs = rawTx.vin.size() == 0;
+    // FundTransaction expects blinding keys, if present, to appear in the output nonces
+    for (auto it = rawTx.vout.begin(); it != rawTx.vout.end(); ++it) {
+        auto search_it = psbt_outs.find(*it);
+        assert (search_it != psbt_outs.end());
+        CPubKey& blind_pub = search_it->second.m_blinding_pubkey;
+        if (blind_pub.IsFullyValid()) {
+            it->nNonce.vchCommitment = std::vector<unsigned char>(blind_pub.begin(), blind_pub.end());
+        }
+    }
```
Comment (achow101) [inline src/wallet/rpcwallet.cpp:4968]: In 70faa7e6b7a4967302154c51a1898d173e594f15 "walletcreatefundedpsbt: signal blinding data correctly to `FundTransaction`"

nit: this could be a range based for loop:

```suggestion
    for (CTxOut& txout : rawTx.vout) {
        auto search_it = psbt_outs.find(txout);
        assert (search_it != psbt_outs.end());
        CPubKey& blind_pub = search_it->second.m_blinding_pubkey;
        if (blind_pub.IsFullyValid()) {
            txout.nNonce.vchCommitment = std::vector<unsigned char>(blind_pub.begin(), blind_pub.end());
        }
    }
```

File: src/wallet/rpcwallet.cpp [hunk 2]
```diff
@@ -4971,6 +4979,17 @@ static RPCHelpMan walletcreatefundedpsbt()
...
+    // It may add outputs (change, and in some edge case OP_RETURN) which need to be
+    // blinded. So pull these into `psbt_outs`.
+    for (auto it = rawTx.vout.begin(); it != rawTx.vout.end(); ++it) {
+        if (!it->nNonce.IsNull() && !psbt_outs.count(*it)) {
+            PSBTOutput new_out{2}; // psbtv2 output
+            new_out.m_blinding_pubkey.Set(it->nNonce.vchCommitment.begin(), it->nNonce.vchCommitment.end());
+            new_out.m_blinder_index = blinder_index;
+            psbt_outs.insert(std::make_pair(*it, new_out));
+        }
+    }
```
Comment (achow101) [inline src/wallet/rpcwallet.cpp:4991]: In 70faa7e6b7a4967302154c51a1898d173e594f15 "walletcreatefundedpsbt: signal blinding data correctly to `FundTransaction`"

nit: This could be a range based for loop:

```suggestion
    for (const CTxOut& txout : rawTx.vout) {
        if (!out.nNonce.IsNull() && !psbt_outs.count(txout)) {
            PSBTOutput new_out{2}; // psbtv2 output
            new_out.m_blinding_pubkey.Set(txout.nNonce.vchCommitment.begin(), txout.nNonce.vchCommitment.end());
            new_out.m_blinder_index = blinder_index;
            psbt_outs.insert(std::make_pair(txout, new_out));
        }
    }
```

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -2859,7 +2859,7 @@ TransactionError CWallet::SignPSBT(PartiallySignedTransaction& psbtx, bool& comp
 
                         CConfidentialNonce nonce;
                         nonce.vchCommitment.insert(nonce.vchCommitment.end(), o.m_ecdh_pubkey.begin(), o.m_ecdh_pubkey.end());
-                        if (!UnblindConfidentialPair(blinding_key, o.m_value_commitment, o.m_asset_commitment, nonce, o.script.get(), o.m_value_rangeproof, value, value_factor, asset, asset_factor)) {
+                        if (UnblindConfidentialPair(blinding_key, o.m_value_commitment, o.m_asset_commitment, nonce, o.script.get(), o.m_value_rangeproof, value, value_factor, asset, asset_factor)) {
```
Comment (achow101) [inline src/wallet/wallet.cpp:2863]: In 96148142e8a575a0aa72fd7579aab6cfb01c4fb4 "wallet: fix "cannot unblind IsMine output" check in SignPSBT"

Is the comment below still true? It seems to me that by changing this check, the assertions below should always be triggered.

Comment (apoelstra) [reply src/wallet/wallet.cpp:2863]: No, the original code was wrong (and it was possible to trigger the assertions)

**Comment by apoelstra** [comment]
@achow101 fixed the loop nits, and changed the two test commits to explicitly check for the output data that we care about.

**Comment by achow101** [comment]
ACK 9eb285c19ddc875985739f4e0289f16e7e5d824f

**Comment by apoelstra** [comment]
The CI failure is a bit mysterious -- I am creating a transaction in the test which spends all a node's money ... in my local tests, every output it has is unblinded, but in CI, some of them are blinded, which results in different behavior. Presumably there is some non-determinism that I need to track down.

**Comment by achow101** [comment]
ACK a67a2df3304d3d02e6d83d5fbf501ffee41a8624
